import { Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/hooks/useAuth";
import { useResponsive } from "@/hooks/use-responsive";
import { useI18n } from "@/lib/i18n";

export default function SettingsScreen(){
 const {user}=useAuth();
 const { horizontalPadding, contentMaxWidth } = useResponsive();
 const { language, setLanguage, t } = useI18n();
 const signOut=async()=>{await supabase.auth.signOut();router.replace("/(auth)/login" as never)};
 return <View style={[s.page,{paddingHorizontal:horizontalPadding,maxWidth:contentMaxWidth,width:"100%",alignSelf:"center"}]}><Pressable onPress={()=>router.back()}><Text style={s.back}>{t("back")}</Text></Pressable><Text style={s.title}>{t("settings")}</Text><View style={s.card}><Text style={s.heading}>{t("account")}</Text><Text style={s.email}>{user?.email||"—"}</Text><Text style={s.info}>{t("emailManaged")}</Text></View><View style={s.card}><Text style={s.heading}>{t("language")}</Text><Text style={s.info}>{t("languageDescription")}</Text><View style={s.languageRow}><Pressable style={[s.languageButton, language === "es" && s.languageButtonActive]} onPress={()=>void setLanguage("es")}><Text style={[s.languageButtonText, language === "es" && s.languageButtonTextActive]}>{t("spanish")}</Text></Pressable><Pressable style={[s.languageButton, language === "en" && s.languageButtonActive]} onPress={()=>void setLanguage("en")}><Text style={[s.languageButtonText, language === "en" && s.languageButtonTextActive]}>{t("english")}</Text></Pressable></View></View><Pressable style={s.row} onPress={()=>router.push("/privacy" as never)}><Text style={s.rowText}>{t("privacy")}</Text><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.row} onPress={()=>router.push("/terms" as never)}><Text style={s.rowText}>{t("terms")}</Text><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.logout} onPress={signOut}><Text style={s.logoutText}>{t("logout")}</Text></Pressable></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#0E0E0E",padding:20,paddingTop:55},back:{color:"#C9A84C",fontWeight:"800",marginBottom:18},title:{color:"#F5F5F5",fontSize:28,fontWeight:"900",marginBottom:20},card:{backgroundColor:"#141414",borderWidth:1,borderColor:"#2A2A2A",borderRadius:12,padding:16,marginBottom:12},heading:{color:"#C9A84C",fontWeight:"900"},email:{color:"#FFF",marginTop:8},info:{color:"#9A9A9A",fontSize:11,lineHeight:17,marginTop:8},row:{backgroundColor:"#171717",borderWidth:1,borderColor:"#2A2A2A",borderRadius:10,padding:16,marginBottom:9,flexDirection:"row",justifyContent:"space-between"},rowText:{color:"#FFF",fontWeight:"700"},arrow:{color:"#C9A84C",fontSize:24},logout:{borderWidth:1,borderColor:"#C9A84C",borderRadius:8,padding:15,alignItems:"center",marginTop:12},logoutText:{color:"#C9A84C",fontWeight:"900"},languageRow:{flexDirection:"row",gap:8,marginTop:12},languageButton:{flex:1,borderWidth:1,borderColor:"#333",borderRadius:8,padding:12,alignItems:"center"},languageButtonActive:{backgroundColor:"#C9A84C",borderColor:"#C9A84C"},languageButtonText:{color:"#FFF",fontWeight:"700"},languageButtonTextActive:{color:"#0E0E0E"}
});